export const GET_RECIPES = 'GET_RECIPES'
export const GET_RECIPE = 'GET_RECIPE'
export const ADD_FAV_RECIPE = 'ADD_FAV_RECIPE'
export const REMOVE_FAV_RECIPE = 'REMOVE_FAV_RECIPE'
export const SET_LOADING = 'SET_LOADING'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_ERROR = 'SET_ERROR'